#! /usr/bin/env sh
#
# osmbtd - OpenStreetMap Batch Traces Download
#
# Author: Julien Sagot
# License: MIT
# Version: 0.2.0
# Homepage: http://github.com/sagotch/osmbtd.sh#README
#
# Usage: osmbtd <tag1> [ ... <tagN> ]
#

# _osmbtd tag start
# Download every traces with a given tag.
# Files are written on disk using the following scheme: ./$user/$gpxid.gpx
#
# $1: tag
# $2: page number where to start.
#     _osmbtd will call itself recursively incrementing this number
#     until it fails. You probably want to start with `_osmbtd tag 1`.
_osmbtd ()
{

    local OSMBASEURL='https://www.openstreetmap.org'
    local tag="$1"
    local page="$2"

    echo "Fetching traces for '$tag' (page $page)"

    local traces="$(curl -s "$OSMBASEURL/traces/tag/$tag/page/$page" \
	| grep -E "/user/[^/]+/traces/[0-9]+" \
	| sed -E 's|.*/user/([^/]+)/traces/([0-9]+).*|\1,\2|' \
	| sort -u)" ;

    if [ x"$traces" != "x" ] ;
    then
	for e in $traces ; do
	    local user=${e%,*}
	    local gpxid=${e#*,}
	    local body="$(mktemp)"
	    local head="$(mktemp)"
	    local output="./$user/$gpxid.gpx"

	    mkdir -p "$user"

	    curl -s -o "$body" -D "$head" "$OSMBASEURL/trace/$gpxid/data"

	    # FIXME: Seems to have strange leading/trailing control character
	    local type="$(grep 'Content-Type:' "$head" | cut -d\  -f2)"

	    case "$type" in
		*application/x-bzip2*)
		    bzip2 -cds "$body" > "$output"  ;;
		*application/x-gzip*)
		    gzip -cdq "$body" > "$output" ;;
		*application/gpx+xml*)
		    cp "$body" "$output" ;;
		*)
		    echo "Content-Type $type is not supported."
		    echo "Please contact osmbtd maintener." ;;
            esac

	    rm "$head" "$body"

	done
	_osmbtd $tag $(( page + 1 ))
    fi
}


# Call _osmbtd on each tag, with ' ' characters replaced by '%20'.
while [ $# -gt 0 ] ; do
    _osmbtd $(echo "$1" | sed 's| |%20|g') 1
    shift
done
